### ISSUE TITLE
Virtualenv - Documentation or Bug... 

### ISSUE THREAD

**Issue by rubenvarela** [oh-my-fish/theme-agnoster#10]
It took me a bit longer that I'd like to admit to find out how to prevent virtualenv from showing the virtualenv name twice. 

So what I did was add to my `init.fish` 

```
#Disable the prompt added by virtualenv when you have a virtualenv active.
set --export VIRTUAL_ENV_DISABLE_PROMPT 'True'
```

&nbsp;

Writing this, I can't help but wonder. Would it be a bad idea to modify the [`prompt_virtual_env`](https://github.com/oh-my-fish/theme-agnoster/blob/master/fish_prompt.fish#L92-L96) function so that inside the `if`, it sets the variable?

**Comment by bpinto** [comment]
ping @bobthecow

**Comment by bobthecow** [comment]
@bpinto this was resolved by #11, i.e. adding to readme rather than modifying `prompt_virtual_env` to change system settings :)

**Comment by rubenvarela** [comment]
I think that's it for this issue. Thank you.

**Comment by bpinto** [comment]
Sorry about that!

**Comment by rubenvarela** [comment]
:) Not at all!
