### ISSUE TITLE
Use --porcelain instead of -s

### ISSUE THREAD

**Issue by ProLoser** [oh-my-fish/theme-agnoster#15]
I have messed with my global config a bit such as setting the short `git status` as my default output as well as a few other tweaks to my global config (I don't remember what they all were exactly). This has broken agnoster as it always shows my git status as modified. If you go back to the original agnoster theme from zsh they are using `--porcelain` which is designed for programmatic consumption and I'd like to propose changing this version too.

**Comment by sn0cr** [comment]
Good point, I may have missed that while porting this theme to fish.
@ProLoser: What do you think about that change?
