### ISSUE TITLE
Missing arrow or separator 

### ISSUE THREAD

**Issue by angstbear** [oh-my-fish/theme-agnoster#21]
![screen shot 2016-09-21 at 11 51 35 am](https://cloud.githubusercontent.com/assets/12141283/18722411/fa12362c-7ff1-11e6-9687-7793272553d9.png)

Anyone know what I'm missing here?

iTerm2 (Build 3.0.8)
Solarized Dark
12pt Meslo for Powerline

**Comment by sn0cr** [comment]
My guesses are you forgot to change the 'non ACII' font in the settings of iTerm. It could also be the case that your powerline font might be outdated (I remember that the glyphs used by powerline were updated).

As I have a second look to your screenshot - if my assumptions would be right - there would be some question marks in between the different segments...

Hope this helps for now.

**Comment by angstbear** [comment]
Before I installed the fonts (https://github.com/powerline/fonts), there were question marks instead of the other symbols. I also experimented with font sizes and different powerline fonts.

Is there a better font source that I should try?

**Comment by angstbear** [comment]
<img width="217" alt="screen shot 2016-09-22 at 8 00 02 pm" src="https://cloud.githubusercontent.com/assets/12141283/18771824/34e38e78-80ff-11e6-8c67-a2403f341fe6.png">

Better now. I tried changing non-ascii fonts, then back to using same font for both, to no avail. All of the sudden it looked better. Possibly just needed to restart iTerm.

**Comment by sn0cr** [comment]
Interesting. Glad that it works now for you.
