### ISSUE TITLE
any setting to display date/time in prompt

### ISSUE THREAD

**Issue by goodloop** [oh-my-fish/theme-agnoster#22]
Hi ,I want to know is there any setting to config the time/date information in prompt?

**Comment by sn0cr** [comment]
I'm afraid there's neither a switch for the date nor the time.
But if you would like it to add, just append the code around these lines:
- [On the left ](https://github.com/oh-my-fish/theme-agnoster/blob/master/fish_prompt.fish#L221)(fish_prompt.fish line 221)
- [On the right](https://github.com/oh-my-fish/theme-agnoster/blob/master/fish_right_prompt.fish#L29)(fish_right_prompt.fish line 29)

**Comment by goodloop** [comment]
add function `fish_right_prompt` in `~/.config/fish/config.fish` seems work for me . thank a lot.

**Comment by sn0cr** [comment]
You're welcome.
