### ISSUE TITLE
Mercurial prompt is slow on big repos

### ISSUE THREAD

**Issue by Strate** [oh-my-fish/theme-agnoster#23]
As for now, there is 4 `hg` invocations used for display mercurial prompt. It could be improved by only 1 `hg prompt` invocation with parsing result.

**Comment by sn0cr** [comment]
I see that is annoying.
Unfortunately I don't use mercurial. @Strate would you like to submit a PR and solve this problem?

**Comment by Strate** [comment]
I also solved this problem by migrate to git :-)
