### ISSUE TITLE
Meslo Font doesn't work for it.

### ISSUE THREAD

**Issue by imkimchi** [oh-my-fish/theme-agnoster#24]
![image](https://cloud.githubusercontent.com/assets/13452168/22091992/9cf77fd0-ddc8-11e6-9bb5-2e4f85d3bd89.png)

I set 12px for ASCII font, 14px for Non-Ascii
and as you see, It doesn't show exact triangle.

**Comment by sn0cr** [comment]
I noticed that too, but that would require a change in the font you chose.
Why is your font size different for non ascii characters?

**Comment by imkimchi** [comment]
@sn0cr I was trying to fix it to change each font size. 
I thought It was a problem caused by font size.

Is it a problem only for mac?

**Comment by sn0cr** [comment]
Ah ok, could've guessed that... I personally can't remember the look of the theme when I used linux, but on my mac it looks the same. 
Maybe someone uses this theme on linux?

**Comment by imkimchi** [comment]
I heard someone says the theme is designed for linux platforms.
so I assume that's why It doesn't work on mac basically

**Comment by sn0cr** [comment]
The only thing that could only fit linux is the font and that can't be changed from my side.
