### ISSUE TITLE
Modifying Theme

### ISSUE THREAD

**Issue by Kalibr8** [oh-my-fish/theme-agnoster#27]
How do I make the theme multiline i.e have the prompt begin on a new line and and add a newline after each prompt/print loop.
Also, how do I modify the default color scheme?

**Comment by sn0cr** [comment]
To make the prompt multiline, add suiting echo here: https://github.com/oh-my-fish/theme-agnoster/blob/557b7b4a01b82a3f95bce64f0c708fddb5a04cb2/fish_prompt.fish#L221

And have a look at the functions there, you can find the color definitions in the function - sadly no configurable color choices at the moment.

**Comment by Kalibr8** [comment]
And what would the appropriate echo be? I ask coz I've tried a few - echo -n "" , echo -n "$" - and they didn't work

**Comment by Kalibr8** [comment]
Never mind. Figured it out. Thanks
