### ISSUE TITLE
change font color

### ISSUE THREAD

**Issue by j-tamad** [oh-my-fish/theme-agnoster#32]
I use a photo for my background, it's mostly very dark grey, but I still can barely read the dark blue font for files when I list files. How can I change it? Sorry, fairly new to fish and omf, so I need explicit instructions.
![screen shot 2018-08-26 at 18 02 45](https://user-images.githubusercontent.com/7821596/44627574-6ddab280-a95a-11e8-9e83-ba3c717c8bb8.png)

**Comment by sn0cr** [comment]
HI @j-tamad,

You can change the color by setting an environment variable in your `config.fish` like so:

```fish
    set -g color_dir_bg red # to set the background of the directory name segment to red
```

If you want to find different variables, have a look at this file: https://github.com/oh-my-fish/theme-agnoster/blob/master/fish_prompt.fish#L23
— But if you mean the colours fish uses, you need to find the settings of your terminal emulator / run `fish_config` to setup a different color mapping
