### ISSUE TITLE
Commandline does not show colors properly

### ISSUE THREAD

**Issue by scwmartinez** [oh-my-fish/theme-agnoster#38]
The commandline does not show colors properly, most of them are opaque than other uses screenshots

![fish](https://user-images.githubusercontent.com/11932167/52361956-351d2a00-2a1e-11e9-84fc-1c28a52ec7b8.png)

**Comment by sn0cr** [comment]
The colours are specific to your terminal emulator and thus dependent on your configuration. — Depending on your system you might want to look into the settings of your terminal emulator.

**Comment by scwmartinez** [comment]
sn0or, thanks for your help!
