### ISSUE TITLE
Please describe how to add git ahead/behind info

### ISSUE THREAD

**Issue by endafarrell** [oh-my-fish/theme-agnoster#42]
With the "Informative + VCS" prompt of fish I had easy visual access to git information which included whether my branch was ahead/behind of the (remote) origin. 

Can you describe how to see that info in agnoster? The yellow color and the plus-minus alone doesn't give me this.

tia!
/e

**Comment by sn0cr** [comment]
I'm not rally sure what you want to know, if you want to add another segment then you can add a function call like ```prompt_segment $color_background $color_foreground $git_symbol_or_output``` to the fish_prompt function in the [fish_prompt.fish](https://github.com/oh-my-fish/theme-agnoster/blob/master/fish_prompt.fish#L275) file.
—- 
Maybe issue #37 could help you a little
