### ISSUE TITLE
putty on windows

### ISSUE THREAD

**Issue by lollilol** [oh-my-fish/theme-agnoster#46]
Theme works fine on my linux machine and when i connect to my server via ssh but when i try to connect to my server via putty on windows it looks like this:
![image](https://user-images.githubusercontent.com/38194372/74609811-f79db300-50ed-11ea-8aa8-5907e0b50dc3.png)

**Comment by sn0cr** [comment]
I would guess that the font you are using for Putty does not support the Powerline characters (as they are custom characters and located in the 'private use' area of UTF). In order to fix this problem you need to install a font for Putty that supports these characters, e.g., on of those: https://github.com/powerline/fonts

**Comment by lollilol** [comment]
Yea installed them
![image](https://user-images.githubusercontent.com/38194372/76334275-1826ea80-62f3-11ea-906b-229a2184f510.png)
But the color still looks weird:
![image](https://user-images.githubusercontent.com/38194372/76334455-5e7c4980-62f3-11ea-9727-cb2f33b6e03c.png)
How can i fix this?
This is how it looks like on my linux machine:
![image](https://user-images.githubusercontent.com/38194372/76337100-30990400-62f7-11ea-8002-ffa0d030a138.png)

**Comment by sn0cr** [comment]
Colours depend on you local configuration, so in order to get the same colours you need to configure the same colours in Putty.
But I don't use Putty nor Windows I can't provide you with hints here.

**Comment by lollilol** [comment]
Aight thanks for your help :)

**Comment by lanyusea** [comment]
@lollilol  @sn0cr 

I installed the same font, the root/error can show correctly but the > is still not correct.

![_20200312_121951](https://user-images.githubusercontent.com/2766729/76486999-f72dd900-645b-11ea-8f2a-ec9b4560408d.png)


any other option needed?

following is my setting:

![_20200312_120505](https://user-images.githubusercontent.com/2766729/76487023-001eaa80-645c-11ea-9bb0-de03a1f1f44b.png)
![_20200312_120519](https://user-images.githubusercontent.com/2766729/76487025-01e86e00-645c-11ea-8d86-e57a27b33280.png)
