### ISSUE TITLE
When typing r in the empty command line carette goes left

### ISSUE THREAD

**Issue by shabashab** [oh-my-fish/theme-agnoster#47]
When i try to type 'r' symbol carette goes left and then when i try to clear that r by holding the backspace button it just starts to clear default line (path, user, git, etc.)
![image](https://user-images.githubusercontent.com/37144124/79641541-ccdce300-81a0-11ea-870d-156b42f8c683.png)

**Comment by sn0cr** [comment]
HI @shabashab, 
I'm not sure where to start to debug this issue -- did you test, if this also happens with other themes in fish?

**Comment by shabashab** [comment]
Yes, it happens with some other themes, not all of fish themes have this issue.

**Comment by sn0cr** [comment]
I tried to reproduce with an 'r' but I just found that it changes nothing (i.e., the most right arrow is still present) -- might want to try to upgrade your fish version? And what terminal are you using? Maybe it could be related to that?

**Comment by shabashab** [comment]
I'm using Windows Terminal with WSL 2 (Ubuntu 18.04)
