### ISSUE TITLE
Add indicator for Private mode

### ISSUE THREAD

**Issue by ayoisaiah** [oh-my-fish/theme-agnoster#49]
If you start fish in private mode (`fish --private`), there's no way to know just by looking at the shell. I think it would be helpful to add such an indicator so it's easy to determine at a glance.

![image](https://user-images.githubusercontent.com/13372163/91441107-8f334980-e867-11ea-9f8b-a203e7e6e4c0.png)

**Comment by sn0cr** [comment]
Sure, I'm happy to merge a PR with this feature!

**Comment by ayoisaiah** [comment]
Something like this make sense?
![image](https://user-images.githubusercontent.com/13372163/91447271-65caeb80-e870-11ea-9508-c719a4224884.png)
