### ISSUE TITLE
Git symbol shown all the time in prompt

### ISSUE THREAD

**Issue by gibbling** [oh-my-fish/theme-agnoster#5]
Hello,

I recently updated omf and after installing agnoster I see the git section of the prompt always.  If I enter an actual repo it shows a second git in the prompt with the name of the branch.  I tried deleting the downloaded theme from the omf themes folder and rerunning omf install to pull it down but it is a persistent problem.

<img width="657" alt="screen shot 2015-08-11 at 2 04 50 am" src="https://cloud.githubusercontent.com/assets/6933314/9191304/8ff7287a-3fcd-11e5-9472-e0e60cba341c.png">

**Comment by gibbling** [comment]
installing bobthefish which is similiar in appearance will only show current directory in the prompt unless its a git repo.  Not sure that helps narrow anything down.

**Comment by makiritare** [comment]
in the fish_prompt.fish

are this lines uncommented?

# set -g theme_display_user yes
# set -g default_user your_normal_user

**Comment by gibbling** [comment]
no those are still commented on the agnoster fish_prompt.fish

**Comment by makiritare** [comment]
try uncommenting and see if there is any change

**Comment by gibbling** [comment]
Same result just with user and machine name included before working dir.

**Comment by sn0cr** [comment]
I just had a look into the theme again, debugged a bit and found that this change was introduced with PR #3

**Comment by sn0cr** [comment]
have a look at this gist, hopefully it solves the problem :smiley: 
https://gist.github.com/sn0cr/44d9351d3ccb365a0bfc

**Comment by gibbling** [comment]
Using that gist instead has solved the problem.  I wonder if this would of been an present if I didn't have svn installed.

**Comment by bpinto** [comment]
@sn0cr Does that gist fix the issue or just "rollback" the changes?

**Comment by gibbling** [comment]
I reverted back to the original fish_prompt.fish after manually gutting svn from osx and the persistent prompt was not present.  I then installed svn via homebrew and it returned.  

I dont want to speak for @sn0cr but it looks like from this diff it just doesn't merge the "if type" and "if command" as one statement.  Looks like this was the original fix mentioned here  https://github.com/oh-my-fish/theme-agnoster/issues/3#issuecomment-125811592

```
<   if type svn >/dev/null 2>&1
<     if command svn ls . >/dev/null 2>&1
<       set branch (svn_get_branch)
<       set branch_symbol \uE0A0
<       set revision (svn_get_revision)
<       prompt_segment green black "$branch_symbol $branch:$revision"
<     end
---
>   if type svn >/dev/null 2>&1; and command svn ls . >/dev/null 2>&1
>     set branch (svn_get_branch)
>     set branch_symbol \uE0A0
>     set revision (svn_get_revision)
>     prompt_segment green black "$branch_symbol $branch:$revision"
```

**Comment by sn0cr** [comment]
Indeed - the 'and' did cause the persistent segment
@bpinto it's a partly rollback - the nested if does solve the issue here - but I don't know why...

**Comment by bpinto** [comment]
I see, submit a PR @sn0cr?

**Comment by sn0cr** [comment]
I think this has been fixed. Closing this for now.
