### ISSUE TITLE
Path of the directory did not shown right

### ISSUE THREAD

**Issue by JensEichbergKugel** [oh-my-fish/theme-agnoster#54]
Im new to fish and omf and want to use the agnoster theme on my MacBook. I install the theme without any problems. But the directory path did not shown in the right style. Is there any terminal setting I have to change?

<img width="946" alt="Bildschirmfoto 2021-11-20 um 17 27 05" src="https://user-images.githubusercontent.com/56768249/142733755-5b58f39c-5a23-4c96-8353-84bda95f5c75.png">

**Comment by sn0cr** [comment]
Yeah, you're missing a Powerline font, change your default terminal font to one of the fonts from here (https://github.com/powerline/fonts) and then you should be able to use it
