### ISSUE TITLE
Do not show while getting root permiission

### ISSUE THREAD

**Issue by lumynou5** [oh-my-fish/theme-agnoster#58]
I used `sudo -s`, and it looks like `root@dname:path# `, not the pretty UI in the example in readme.

![image](https://user-images.githubusercontent.com/84374077/163707815-5c80347f-0a9d-4f59-bd3f-422c3f43b66f.png)

**Comment by sn0cr** [comment]
Hi @Luminous-Coder, if I remember correctly (the screenshot is now many years old) you also need to setup the shell on the root user. For more information I would have a look at the man page of `sudo` how `sudo -s` works.

**Comment by lumynou5** [comment]
> Hi @Luminous-Coder, if I remember correctly (the screenshot is now many years old) you also need to setup the shell on the root user. For more information I would have a look at the man page of `sudo` how `sudo -s` works.

Thanks.
BTW, does setting fish for root user has any other side effect?

**Comment by sn0cr** [comment]
I don't think so, as the shell that is set in `/etc/passwd` is only used interactively and not in scripts, I assume. So hopefully without side effects.
