### ISSUE TITLE
Do not show icons.

### ISSUE THREAD

**Issue by onur-tlntmr** [oh-my-fish/theme-agnoster#59]
Hi,
I installed fonts-powerline, fish and agnoster theme but icons are not showing. Can you help me ? 

![image](https://user-images.githubusercontent.com/28988388/164430033-5f44efc9-07da-4780-aad6-605e37602850.png)

Powerline checks: 
![image](https://user-images.githubusercontent.com/28988388/164430402-487f0063-7af0-4a1f-ba84-3fb7cdc75e63.png)

Finally neofetch: 

![image](https://user-images.githubusercontent.com/28988388/164431483-8287c044-f28c-4e20-ac7b-8eef07d66d54.png)

**Comment by sn0cr** [comment]
As you seem to have a Powerline font, I can only assume that either your font uses older codepoints -- or we are using older ones. Did you use the font repo that is linked in the Readme?

**Comment by onur-tlntmr** [comment]
Yes I had it installed, now I've updated to ubuntu 22.04 and it doesn't seem to have any issues thanks.
