### ISSUE TITLE
feat: add shortening of long branch names

### ISSUE THREAD

**Issue by elagil** [oh-my-fish/theme-agnoster#61]
In some cases, branch names are so long that they leave no space for typing anymore.

Let's take the example of a short branch name, where there is no problem:
![grafik](https://user-images.githubusercontent.com/9093113/199321753-4a461b4a-d0f0-41c4-997d-0987b582c1f0.png)

However, I sometimes have long branch names, so that they leave no space in the command line:
![grafik](https://user-images.githubusercontent.com/9093113/199321720-f5b73c3b-4dbd-4e23-8ebf-f1be862988e7.png)

So, I suggest to (optionally) shorten the branch name, if desired.
![grafik](https://user-images.githubusercontent.com/9093113/199321886-ef30fa5b-44d8-46b8-a348-f3fa2de1ae68.png)

What do you think? I can create a PR.
The idea is, to specify a maximum branch length name in the fish config (e.g. 12), above which a branch name is shortened. The default setting would be to display the full branch name.

**Comment by sn0cr** [comment]
Hi @elagil, that sounds really good.

I'm happy to merge a PR adding this functionality.

**Comment by elagil** [comment]
Great, I will prepare something

**Comment by elagil** [comment]
Here you go: https://github.com/oh-my-fish/theme-agnoster/pull/65

Please let me know, if I shall change something. It should work for all version control systems, but I can only test git myself.
