### ISSUE TITLE
Awkward Conda Integration

### ISSUE THREAD

**Issue by Nosamdaman** [oh-my-fish/theme-agnoster#66]
I love the new python virtual environment prompt, but I think having it come before the user and host name segment is less than ideal. By default, the user and host name segment use the same colors as the status segment, but with the conda segment between them, you can have awkward looking prompts like this:

![image](https://user-images.githubusercontent.com/54364725/219665795-0d28fa47-c3b6-4bf6-bbdb-e846c439b2d3.png)

I think it would fit better after the hostname and potentially even the path segment.

**Comment by sn0cr** [comment]
Thank you for reaching out! I agree that splitting this does not look so appealing. Do you want to go ahead and adapt the order in the [fish_prompt.fish](https://github.com/oh-my-fish/theme-agnoster/blob/master/functions/fish_prompt.fish#L330)?

**Comment by Nosamdaman** [comment]
> Thank you for reaching out! I agree that splitting this does not look so appealing. Do you want to go ahead and adapt the order in the [fish_prompt.fish](https://github.com/oh-my-fish/theme-agnoster/blob/master/functions/fish_prompt.fish#L330)?

Done, see #67
