### ISSUE TITLE
weird symbols in prompt

### ISSUE THREAD

**Issue by Cerealkillerway** [oh-my-fish/theme-agnoster#7]
I get strange symbols in prompt whil using agnoster theme

![Weird prompt](http://i.stack.imgur.com/qJ84a.jpg)

I'm using fish 2.0.0 with oh-my-fish 1.0.0

**Comment by derekstavis** [comment]
Probably the font you are using don't support powerline symbols. Give a look at some fonts that suppor them here (monospaced section): https://github.com/derekstavis/awesome-font

**Comment by Cerealkillerway** [comment]
right, thank you for help
